# Generated by Django 2.2.6 on 2020-02-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_songs_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='file_type',
        ),
        migrations.AddField(
            model_name='songs',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
